apiVersion: apps/v1
kind: Deployment

metadata:
  name: gows

spec:
  selector:
    matchLabels:
      app: gows-app
      version: "1.0.0"

  replicas: 1

  template:
    metadata:
      labels:
        app: gows-app
        version: "1.0.0"

    spec:
      containers:
      - name: gows-app
        image: jhonatanrs/ms-backend-test:1.0.0
        resources:
          limits:
            memory: "50Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: gows-configmap
          - secretRef:
              name: gows-secrets

        # env:
        #   - name: APP_VERSION
        #     valueFrom:
        #       configMapKeyRef:
        #         name: gows-configmap
        #         key: APP_VERSION

        #   - name: APP_PORT
        #     valueFrom:
        #       configMapKeyRef:
        #         name: gows-configmap
        #         key: APP_PORT

        volumeMounts:
          - mountPath: "/app/files"
            name: numbers-configmap
            readOnly: true

      volumes:
        - name: numbers-configmap
          configMap:
            name: numbers
            items:
              - key: numbers
                path: "numbers.txt"

---
apiVersion: v1
kind: Service

metadata:
  name: gows-service

spec:
  # Tipos suportados de serviços
  # ClusterIP, NodePort, LoadBalancer, Heeadless
  # NodePort tem um range de portas externas suportadas: 30000 - 32767
  type: ClusterIP
  selector:
    app: gows-app

  ports:
  - name: gows-http
    port: 80
    targetPort: 80
    # nodePort: 30000
