apiVersion: apps/v1
kind: Deployment

metadata:
  name: ws

spec:
  selector:
    matchLabels:
      app: ws-app
      version: "1.0.0"

  replicas: 1

  template:
    metadata:
      labels:
        app: ws-app
        version: "1.0.0"

    spec:
      containers:
      - name: ws-app
        image: jhonatanrs/ms-backend-istio:1.0.0
        resources:
          limits:
            memory: "50Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
        env:
          - name: APP_VERSION
            value: "2.0.0"
          - name: APP_PORT
            value: ":80"

---
apiVersion: v1
kind: Service

metadata:
  name: ws-service

spec:
  # Tipos suportados de serviços
  # ClusterIP, NodePort, LoadBalancer, Heeadless
  # NodePort tem um range de portas externas suportadas: 30000 - 32767
  type: ClusterIP
  selector:
    app: ws-app

  ports:
  - name: ws-http
    port: 80
    targetPort: 80
