apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: jrstech.com.br
  labels:
    name: jrstech.com.br

spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gows-service
            port:
              number: 80

  - host: gows.jrstech.com.br
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: gows-service
            port: 
              number: 80

  - host: ws.jrstech.com.br
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ws-service
            port: 
              number: 80

# Depois de configurar o ingress podemos editar o arquivo de hosts com o ip do ingress.
# kubectl get ingress